name: Test and Deploy

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: chmod +x ./node_modules/.bin/jest
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: .
      - uses: actions/create-pages-site@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: . 
          publish_dir: /
