name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git config
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name "BanderlogCumberbatch"
      - run: ls -l
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Grant permissions
        run: chmod +x ./node_modules/.bin/jest
      - run: ls -l
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: .
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # Директория, где собраны файлы сайта
          user_name: 'BanderlogCumberbatch'
          # Имя пользователя GitHub
          repo_name: 'BanderlogCumberbatch.github.io'
          # Имя репозитория GitHub Pages
          publish_branch: gh-pages 
